FROM wordpress:6.1.1-php8.2-apache

COPY plugins /var/www/html/wp-content/plugins
COPY themes /var/www/html/wp-content/themes
COPY uploads /var/www/html/wp-content/uploads
COPY woocommerce-uploads /var/www/html/wp-content/uploads/woocommerce-uploads