FROM wordpress:5.9.3-php8.0-apache

COPY plugins /var/www/html/wp-content/plugins
COPY themes /var/www/html/wp-content/themes
COPY uploads /var/www/html/wp-content/uploads
COPY woocommerce-uploads /var/www/html/wp-content/uploads/woocommerce-uploads